# Generated by Django 4.2.10 on 2024-03-07 03:53

from django.db import migrations, models
import recipies_list_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipies_data',
            fields=[
                ('recipie_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipie_name', models.CharField(max_length=100)),
                ('recipie_description', models.CharField(max_length=400)),
                ('recipie_duration', models.IntegerField()),
                ('recipie_ingredients', models.CharField(max_length=800)),
                ('recipie_steps', models.TextField()),
                ('recipie_photo', models.FileField(null=True, upload_to=recipies_list_app.models.user_directory_path, verbose_name='')),
            ],
            options={
                'db_table': 'recipies',
            },
        ),
    ]
